HS serialization intermediate PR
OpenTrons/opentrons-modules pull request #195
Opened 2021-08-18 19:23 UTC by pmoegenburg

Some implementing of details and cleanup still needs to be done, but code basically works and current tests pass

2021-08-18 19:28 UTC, sfoster1 requested changes
We should change the CMakePresets.json to select the `MinSizeRel` `CMAKE_BUILD_CONFIG`

Also some cleanup notes.

But the structure looks great, nice work!

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/firmware/system/STM32F303RETx_FLASH.ld
> -FLASH (rx)      : ORIGIN = 0x08000000, LENGTH = 512K
let's leave a comment here about why the change happens and when we should change it back (is it necessary now that we're not near the limit?)

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/firmware/system/system_policy.cpp
> +#include <array>
don't think we need these right? and cleanup

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/firmware/system/system_policy.hpp
> +#include "system_hardware.h"
Rather than doing this, let's but the implementation of these methods in the `.cpp`

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/firmware/system/system_serial_number.c
> +//static uint8_t Serial_Number[] = (uint8_t*)0x0805F800;
cleanup

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/firmware/system/system_serial_number.h
> +bool system_set_serial_number(uint64_t to_write);
This is the core of the current limitation to at most 8 characters; we should think about whether we want to extent this, and how we might do it.

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/include/heater-shaker/gcodes.hpp
> +        //do we need to do anything with value_res.second?
cleanup commented out code

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/include/heater-shaker/messages.hpp
> +    static constexpr std::size_t serial_number_length = 8;
we might want to derive this length or store it from some single source of truth at least for all the template arguments

2021-08-18 19:28 UTC, sfoster1 commented on stm32-modules/heater-shaker/include/heater-shaker/system_task.hpp
> +//std::array<char,8> TestArr = {"TESTSNX"};
cleanup

2021-09-28 20:20 UTC, pmoegenburg commented
not sure how to properly link this with Jira RET-2 ticket

2021-09-28 20:31 UTC, sfoster1 approved these changes
Looks good so far!

2021-09-28 20:31 UTC, sfoster1 commented on stm32-modules/heater-shaker/firmware/system/system_policy.hpp
> +    static constexpr std::size_t system_serial_number_length =
Can we make these constants `NAMED_LIKE_THIS` so it's a bit more apparent in the moment that they're constants

2021-09-29 21:05 UTC, merged