fix(heater-shaker): add post homing delay
OpenTrons/opentrons-modules pull request #338
Opened 2022-07-02 23:05 UTC by pmoegenburg

Homing gcode immediately followed by SetRPM produced a `motor unable to move` error.

This fix introduces a delay at the end of the homing sequence to ensure motor control is fully deactivated before subsequent SetRPM commands may be executed.

Closes Opentrons/opentrons #10858

2022-07-05 13:15 UTC, fsinapi approved these changes
LGTM

2022-07-05 14:08 UTC, sfoster1 requested changes
Solution looks good, but that error handling thing really needs a comment and probably a test.

2022-07-05 14:08 UTC, sfoster1 commented on stm32-modules/include/heater-shaker/heater-shaker/motor_task.hpp
> +                error = (error == errors::ErrorCode::NO_ERROR)
why do we have to do this? if it's the underlying driver doing something weird, let's drop a comment to that effect here and add a test.

2022-07-06 21:34 UTC, sfoster1 approved these changes
Looks good to me!

2022-07-06 21:36 UTC, merged

2022-07-07 20:30 UTC, sanni-t commented
Thanks for fixing this!