fix(heater-shaker): return EMPTYSN to M115 if serial number not programmed
OpenTrons/opentrons-modules pull request #355
Opened 2022-07-23 22:43 UTC by pmoegenburg

2022-07-25 12:53 UTC, fsinapi approved these changes
LGTM!

2022-07-25 13:14 UTC, sfoster1 requested changes
Let's definitely do a quick change to avoid poking stl internals. I think the actual logic would be better off checking for `0xff` explicitly rather than "anything that's not a 7 bit ascii" but if it works it's ok to not change it.

2022-07-25 13:14 UTC, sfoster1 commented on stm32-modules/heater-shaker/tests/test_m115.cpp
> +            memset(TEST_SN._M_elems, 0xFF, TEST_SN.size());
whoa whoa we definitely should not be poking STL internals. arrays don't have convenient ctors but what they do have is [fill](https://en.cppreference.com/w/cpp/container/array/fill) which should do what you want

2022-07-25 13:14 UTC, sfoster1 commented on stm32-modules/include/heater-shaker/heater-shaker/gcodes.hpp
> +        constexpr uint8_t invalid_ascii_mask = 0x80;
Let's not overcomplicate this - let's just look for the first exact match for `0xff`.

2022-07-26 15:49 UTC, sfoster1 approved these changes
Looks good to me!

2022-07-26 16:01 UTC, merged