feat(flex-stacker): add the motor stallguard functionality and gcodes.
OpenTrons/opentrons-modules pull request #466
Opened 2024-09-30 20:53 UTC by vegano1

# Overview

The Flex Stacker motors do not have encoders on them so we can't use the same method we use for the Flex firmware to detect stalls, fortunately, the TMC2160 motors have a stall detection mechanism called `StallGuard` which uses back EMF to detect load changes. This pull request exposes the stall guard feature and takes advantage of the `diag0` pin to stop the motors in case of a stall. We then also provide a new `M910: SetMotorStallGuard` to enable and set each motor's Stall Guard Threshold (SGT) value to allow hardware testing to tune the values.

Closes: [PLAT-509](https://opentrons.atlassian.net/browse/PLAT-509)

# Changelog

- Enable diag0 pin by changing the `TCOOLTHRS > TSTEP` value to `0x2FF`
- Enable diag0_stall for all motors in the GCONF (0x00) register
- Enable the Stall Guard Threshold sgt value in the COOLCONF (0x6D) register
- Added an interrupt to listen to diag0 pin, which sends a `GPIOInterruptMessage` to the `motor_task`
- Handle the `GIOInterruptMessage` in the `motor_task` which stops the motors from running.
- Add new gcode `M910: SetMotorStallGuard` to enable/disable and set each motor's Stall Guard Threshold (SGT) value

# Testing

- [ ] Make sure that the motors do not stop when held if stallguard Is disabled with `M910`
- [ ] Make sure that we can change the stallguard sensitivity with `M910` and that the motors stops when held

# Review Requests

- Makes sense?
- Anything I'm missing?

2024-10-01 15:09 UTC, ahiuchingau commented on stm32-modules/include/flex-stacker/flex-stacker/motor_driver_task.hpp
> +            if (m.sgt.value() >= -64 && m.sgt.value() <= 63) {
Can we make these magic numbers constants?

2024-10-01 15:31 UTC, ahiuchingau requested changes
Implementing the `aggregator.send_from_isr` is ingenious! I didn't think of that.

Got a couple of questions. Mainly not sure if we want to disable the X (and L, but I'm not as concerned about that) motors since they don't have brakes and the axis has a pretty strong spring that might displace the motor.

2024-10-01 15:31 UTC, ahiuchingau commented on stm32-modules/flex-stacker/firmware/motor_control/motor_hardware.c
> +    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
Do we want to enable this interrupt all the time? Or should we only do it when we tell the motor driver to enable to the diag pin? I'm only concerned about this because i'm not sure how noisy this line is

2024-10-01 15:31 UTC, ahiuchingau commented on stm32-modules/include/flex-stacker/firmware/motor_interrupt.hpp
> +        _policy->disable_motor(_id);
Not entirely sure if we want to disable all the motors since we'll need the X and L to be holding as they don't have brakes. Can we call stop motor instead?

2024-10-08 18:12 UTC, vegano1 commented on stm32-modules/flex-stacker/firmware/motor_control/motor_hardware.c
> +    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
fixed, nice callout

2024-10-11 16:08 UTC, ahiuchingau approved these changes
💂💂💂

2024-10-11 17:13 UTC, merged